#!/usr/bin/env bash
# 404 page not found

apt-get -y update
apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sed -i '38i\rewrite /^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" >> /etc/nginx/html/custom_404.html
sed -i '39i\error_page 404 /custom_404.html' /etc/nginx/sites-available/default
service nginx start
