#!/usr/bin/env bash
# Handles Process and PID file

num="1"
sudo touch /var/run/myscript.pid
sudo bash -c 'echo $$ > /var/run/myscript.pid'
while [ $num -eq 1 ]
do
echo "To infinity and beyond"
sleep 2
trap 'echo "Y U no love me?!"; exit' SIGINT
trap 'echo "I hate the kill command"; sudo rm var/run/myscript.pid; exit' SIGTERM
trap 'sudo rm /var/run/myscript.pid; exit' SIGQUIT
done
